import type { OfficialThemeSkin } from './types';

export const blossomSkin: OfficialThemeSkin = {
  id: 'blossom',
  className: 'theme-skin-blossom',
  vars: {
    '--official-control-bg': 'rgb(255, 255, 255)',
    '--official-control-color': 'rgba(0, 0, 0, 0.88)',
    '--official-control-border-color': 'rgb(217, 217, 217)',
    '--official-control-border-width': '1px',
    '--official-control-radius': '16px',
    '--official-control-height': '32px',
    '--official-control-shadow': 'none',
    '--official-placeholder-color': 'rgba(0, 0, 0, 0.25)',
    '--official-primary-bg': 'rgb(237, 65, 146)',
    '--official-primary-border-color': 'transparent',
    '--official-primary-color': '#fff',
    '--official-button-radius': '8px',
    '--official-button-border-width': '1px',
    '--official-primary-shadow': 'rgba(255, 5, 72, 0.06) 0 2px 0',
    '--official-button-font-weight': '400',
    '--official-button-text-transform': 'none',
    '--official-danger-bg': '#fff',
    '--official-danger-color': 'rgb(255, 77, 79)',
    '--official-danger-border-color': 'rgb(255, 77, 79)',
    '--official-danger-radius': '16px',
    '--official-danger-shadow': 'rgba(255, 38, 5, 0.06) 0 2px 0',
    '--official-checkbox-radius': '4px',
    '--official-scene-bg': 'url("https://mdn.alipayobjects.com/huamei_7uahnr/afts/img/A*s5OdR6wZZIkAAAAAAAAAAAAADrJ8AQ/fmt.webp")',
    '--official-preview-panel-bg': 'rgb(255, 247, 251)',
    '--official-preview-panel-border': '1px solid rgb(255, 214, 231)',
    '--official-preview-panel-radius': '16px',
    '--official-preview-panel-shadow': 'rgba(237, 65, 146, 0.12) 0 12px 30px',
    '--official-surface-bg': 'rgb(255, 247, 251)',
    '--official-surface-border': '1px solid rgb(255, 214, 231)',
    '--official-surface-radius': '16px',
    '--official-surface-shadow': 'rgba(237, 65, 146, 0.12) 0 12px 30px',
    '--official-segmented-bg': 'rgba(0, 0, 0, 0.04)',
    '--official-segmented-selected-bg': 'rgb(255, 255, 255)',
    '--official-font-family': 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
};
