import type { OfficialThemeSkin } from './types';

export const bootstrapSkin: OfficialThemeSkin = {
  id: 'bootstrap',
  className: 'theme-skin-bootstrap',
  vars: {
    '--official-control-bg': 'rgb(255, 255, 255)',
    '--official-control-color': 'rgba(0, 0, 0, 0.88)',
    '--official-control-border-color': 'rgb(217, 217, 217)',
    '--official-control-border-width': '1px',
    '--official-control-radius': '4px',
    '--official-control-height': '32px',
    '--official-control-shadow': 'none',
    '--official-placeholder-color': 'rgba(0, 0, 0, 0.25)',
    '--official-primary-bg': 'rgb(22, 119, 255)',
    '--official-primary-border-color': 'rgba(0, 0, 0, 0.3)',
    '--official-primary-color': '#fff',
    '--official-button-radius': '4px',
    '--official-button-border-width': '1px',
    '--official-primary-shadow': 'rgba(255, 255, 255, 0.15) 0 1px 0 inset',
    '--official-button-font-weight': '400',
    '--official-button-text-transform': 'none',
    '--official-danger-bg': '#fff',
    '--official-danger-color': 'rgb(255, 77, 79)',
    '--official-danger-border-color': 'rgba(0, 0, 0, 0.3)',
    '--official-danger-radius': '4px',
    '--official-danger-shadow': 'var(--official-primary-shadow)',
    '--official-switch-shadow': 'rgba(0, 0, 0, 0.4) 0 1px 3px inset',
    '--official-checkbox-radius': '4px',
    '--official-scene-bg': 'linear-gradient(135deg, #eef8ff 0%, #ffffff 45%, #f4fbff 100%)',
    '--official-preview-panel-bg': 'rgb(255, 255, 255)',
    '--official-preview-panel-border': '1px solid rgb(222, 226, 230)',
    '--official-preview-panel-radius': '6px',
    '--official-preview-panel-shadow': 'rgba(0, 0, 0, 0.075) 0 0.5rem 1rem',
    '--official-surface-bg': 'rgb(255, 255, 255)',
    '--official-surface-border': '1px solid rgb(222, 226, 230)',
    '--official-surface-radius': '6px',
    '--official-surface-shadow': 'rgba(0, 0, 0, 0.075) 0 0.5rem 1rem',
    '--official-segmented-bg': 'rgba(0, 0, 0, 0.04)',
    '--official-segmented-selected-bg': 'rgb(255, 255, 255)',
    '--official-font-family': 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
};
