import type { OfficialThemeSkin } from './types';

export const cartoonSkin: OfficialThemeSkin = {
  id: 'cartoon',
  className: 'theme-skin-cartoon',
  vars: {
    '--official-control-bg': 'rgb(245, 245, 243)',
    '--official-control-color': 'rgb(81, 70, 59)',
    '--official-control-border-color': 'rgb(34, 85, 85)',
    '--official-control-border-width': '2px',
    '--official-control-radius': '18px',
    '--official-control-height': '36px',
    '--official-control-shadow': 'none',
    '--official-placeholder-color': 'rgba(0, 0, 0, 0.25)',
    '--official-primary-bg': 'rgb(34, 85, 85)',
    '--official-primary-border-color': 'transparent',
    '--official-primary-color': '#fff',
    '--official-button-radius': '18px',
    '--official-button-border-width': '2px',
    '--official-primary-shadow': 'none',
    '--official-button-font-weight': '400',
    '--official-button-text-transform': 'none',
    '--official-danger-bg': 'rgb(245, 245, 243)',
    '--official-danger-color': 'rgb(218, 135, 135)',
    '--official-danger-border-color': 'rgb(218, 135, 135)',
    '--official-danger-radius': '18px',
    '--official-danger-border-width': '2px',
    '--official-danger-shadow': 'none',
    '--official-checkbox-radius': '6px',
    '--official-scene-bg': 'url("https://mdn.alipayobjects.com/huamei_iwk9zp/afts/img/A*tgpBT7vYIUsAAAAAQ-AAAAgAegCCAQ/original")',
    '--official-preview-panel-bg': 'rgb(187, 170, 153)',
    '--official-preview-panel-border': '2px solid rgb(81, 70, 59)',
    '--official-preview-panel-radius': '18px',
    '--official-preview-panel-shadow': 'none',
    '--official-surface-bg': 'rgb(187, 170, 153)',
    '--official-surface-border': '2px solid rgb(81, 70, 59)',
    '--official-surface-radius': '18px',
    '--official-surface-shadow': 'none',
    '--official-segmented-bg': 'rgba(0, 0, 0, 0.04)',
    '--official-segmented-selected-bg': 'rgb(255, 255, 255)',
    '--official-font-family': 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
};
