import type { OfficialThemeSkin } from './types';

export const coffeeSkin: OfficialThemeSkin = {
  id: 'coffee',
  className: 'theme-skin-coffee',
  vars: {
    '--official-control-bg': 'rgb(252, 250, 248)',
    '--official-control-color': 'rgb(42, 35, 29)',
    '--official-control-border-color': 'rgb(226, 220, 213)',
    '--official-control-border-width': '1px',
    '--official-control-radius': '4px',
    '--official-control-height': '32px',
    '--official-control-shadow': 'none',
    '--official-placeholder-color': 'rgb(196, 186, 176)',
    '--official-primary-bg': 'rgb(49, 39, 33)',
    '--official-primary-border-color': 'transparent',
    '--official-primary-color': '#fff',
    '--official-button-radius': '4px',
    '--official-button-border-width': '1px',
    '--official-primary-shadow': 'none',
    '--official-button-font-weight': '500',
    '--official-button-text-transform': 'none',
    '--official-danger-bg': 'rgb(252, 250, 248)',
    '--official-danger-color': 'rgb(190, 66, 55)',
    '--official-danger-border-color': 'rgb(190, 66, 55)',
    '--official-danger-radius': '4px',
    '--official-danger-shadow': 'none',
    '--official-checkbox-radius': '4px',
    '--official-scene-bg': 'linear-gradient(135deg, #f7f1ea 0%, #fcfaf8 45%, #efe3d7 100%)',
    '--official-preview-panel-bg': 'rgb(252, 250, 248)',
    '--official-preview-panel-border': '1px solid rgb(226, 220, 213)',
    '--official-preview-panel-radius': '4px',
    '--official-preview-panel-shadow': 'rgba(49, 39, 33, 0.1) 0 12px 32px',
    '--official-surface-bg': 'rgb(252, 250, 248)',
    '--official-surface-border': '1px solid rgb(226, 220, 213)',
    '--official-surface-radius': '4px',
    '--official-surface-shadow': 'rgba(49, 39, 33, 0.1) 0 12px 32px',
    '--official-segmented-bg': 'rgba(0, 0, 0, 0.04)',
    '--official-segmented-selected-bg': 'rgb(255, 255, 255)',
    '--official-font-family': 'Inter, -apple-system, system-ui, "Segoe UI", sans-serif',
  },
};
