import type { OfficialThemeSkin } from './types';

export const defaultSkin: OfficialThemeSkin = {
  id: 'default',
  className: 'theme-skin-default',
  vars: {
    '--official-control-bg': 'rgb(255, 255, 255)',
    '--official-control-color': 'rgba(0, 0, 0, 0.88)',
    '--official-control-border-color': 'rgb(217, 217, 217)',
    '--official-control-border-width': '1px',
    '--official-control-radius': '6px',
    '--official-control-height': '32px',
    '--official-control-shadow': 'none',
    '--official-placeholder-color': 'rgba(0, 0, 0, 0.25)',
    '--official-primary-bg': 'rgb(22, 119, 255)',
    '--official-primary-border-color': 'transparent',
    '--official-primary-color': '#fff',
    '--official-button-radius': '4px',
    '--official-button-border-width': '1px',
    '--official-primary-shadow': 'rgba(5, 145, 255, 0.1) 0 2px 0',
    '--official-button-font-weight': '400',
    '--official-button-text-transform': 'none',
    '--official-danger-bg': 'rgb(255, 255, 255)',
    '--official-danger-color': 'rgb(255, 77, 79)',
    '--official-danger-border-color': 'rgb(255, 77, 79)',
    '--official-danger-radius': '6px',
    '--official-danger-shadow': 'rgba(255, 38, 5, 0.06) 0 2px 0',
    '--official-checkbox-radius': '4px',
    '--official-scene-bg': 'url("https://mdn.alipayobjects.com/huamei_iwk9zp/afts/img/A*T8IlRaNez08AAAAARwAAAAgAegCCAQ/original")',
    '--official-preview-panel-bg': 'rgba(255, 255, 255, 0.58)',
    '--official-preview-panel-border': '1px solid rgba(164, 211, 232, 0.42)',
    '--official-preview-panel-radius': '24px',
    '--official-preview-panel-shadow': 'rgba(70, 105, 120, 0.14) 0 22px 60px',
    '--official-surface-bg': 'rgba(255, 255, 255, 0.58)',
    '--official-surface-border': '1px solid rgba(164, 211, 232, 0.42)',
    '--official-surface-radius': '24px',
    '--official-surface-shadow': 'rgba(70, 105, 120, 0.14) 0 22px 60px',
    '--official-segmented-bg': 'rgba(0, 0, 0, 0.04)',
    '--official-segmented-selected-bg': 'rgb(255, 255, 255)',
    '--official-font-family': 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
};
