import type { OfficialThemeSkin } from './types';

export const geekSkin: OfficialThemeSkin = {
  id: 'geek',
  className: 'theme-skin-geek',
  vars: {
    '--official-control-bg': 'rgb(20, 20, 20)',
    '--official-control-color': 'rgb(57, 255, 20)',
    '--official-control-border-color': 'rgb(51, 220, 20)',
    '--official-control-border-width': '2px',
    '--official-control-radius': '0',
    '--official-control-height': '34px',
    '--official-control-shadow': 'rgb(51, 220, 20) 0 0 3px, rgb(51, 220, 20) 0 0 10px inset',
    '--official-placeholder-color': 'rgba(255, 255, 255, 0.25)',
    '--official-primary-bg': 'rgb(51, 220, 20)',
    '--official-primary-border-color': 'transparent',
    '--official-primary-color': 'rgb(20, 20, 20)',
    '--official-button-radius': '0',
    '--official-button-border-width': '0',
    '--official-primary-shadow': 'var(--official-control-shadow)',
    '--official-button-font-weight': '700',
    '--official-button-text-transform': 'none',
    '--official-danger-bg': 'rgb(20, 20, 20)',
    '--official-danger-color': 'rgb(220, 68, 70)',
    '--official-danger-border-color': 'rgb(51, 220, 20)',
    '--official-danger-radius': '0',
    '--official-danger-border-width': '2px',
    '--official-danger-shadow': 'var(--official-control-shadow)',
    '--official-checkbox-radius': '0',
    '--official-scene-bg': 'url("https://mdn.alipayobjects.com/huamei_iwk9zp/afts/img/A*fzA2T4ms154AAAAARtAAAAgAegCCAQ/original")',
    '--official-preview-panel-bg': 'rgb(20, 20, 20)',
    '--official-preview-panel-border': '1px solid rgb(57, 255, 20)',
    '--official-preview-panel-radius': '0',
    '--official-preview-panel-shadow': 'rgba(51, 220, 20, 0.2) 0 0 18px',
    '--official-surface-bg': 'rgb(20, 20, 20)',
    '--official-surface-border': '1px solid rgb(57, 255, 20)',
    '--official-surface-radius': '0',
    '--official-surface-shadow': 'rgba(51, 220, 20, 0.2) 0 0 18px',
    '--official-segmented-bg': 'rgba(255, 255, 255, 0.08)',
    '--official-segmented-selected-bg': 'rgba(255, 255, 255, 0.16)',
    '--official-font-family': 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
};
