import type { OfficialThemeSkin } from './types';

export const illustrationSkin: OfficialThemeSkin = {
  id: 'illustration',
  className: 'theme-skin-illustration',
  vars: {
    '--official-control-bg': 'rgb(255, 255, 255)',
    '--official-control-color': 'rgb(44, 44, 44)',
    '--official-control-border-color': 'rgb(44, 44, 44)',
    '--official-control-border-width': '3px',
    '--official-control-radius': '12px',
    '--official-control-height': '42px',
    '--official-control-shadow': 'rgb(44, 44, 44) 4px 4px 0',
    '--official-placeholder-color': 'rgba(0, 0, 0, 0.25)',
    '--official-primary-bg': 'rgb(82, 196, 26)',
    '--official-primary-border-color': 'rgb(44, 44, 44)',
    '--official-primary-color': '#fff',
    '--official-button-radius': '8px',
    '--official-button-border-width': '3px',
    '--official-primary-shadow': 'rgb(44, 44, 44) 4px 4px 0',
    '--official-button-font-weight': '600',
    '--official-button-text-transform': 'uppercase',
    '--official-danger-bg': '#fff',
    '--official-danger-color': 'rgb(250, 82, 82)',
    '--official-danger-border-color': 'rgb(44, 44, 44)',
    '--official-danger-radius': '12px',
    '--official-danger-border-width': '3px',
    '--official-danger-shadow': 'rgb(44, 44, 44) 4px 4px 0',
    '--official-danger-font-weight': '600',
    '--official-danger-text-transform': 'uppercase',
    '--official-checkbox-radius': '4px',
    '--official-scene-bg': 'url("https://mdn.alipayobjects.com/huamei_iwk9zp/afts/img/A*HuVGQKqOER0AAAAARsAAAAgAegCCAQ/original")',
    '--official-preview-panel-bg': 'rgb(255, 240, 246)',
    '--official-preview-panel-border': '3px solid rgb(44, 44, 44)',
    '--official-preview-panel-radius': '16px',
    '--official-preview-panel-shadow': 'rgb(44, 44, 44) 4px 4px 0',
    '--official-surface-bg': 'rgb(255, 240, 246)',
    '--official-surface-border': '3px solid rgb(44, 44, 44)',
    '--official-surface-radius': '16px',
    '--official-surface-shadow': 'rgb(44, 44, 44) 4px 4px 0',
    '--official-segmented-bg': 'rgba(0, 0, 0, 0.04)',
    '--official-segmented-selected-bg': 'rgb(255, 255, 255)',
    '--official-font-family': 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
};
