import type { OfficialThemeSkin } from './types';

export const larkSkin: OfficialThemeSkin = {
  id: 'lark',
  className: 'theme-skin-lark',
  vars: {
    '--official-control-bg': 'rgb(255, 255, 255)',
    '--official-control-color': 'rgba(0, 0, 0, 0.88)',
    '--official-control-border-color': 'rgb(217, 217, 217)',
    '--official-control-border-width': '1px',
    '--official-control-radius': '4px',
    '--official-control-height': '32px',
    '--official-control-shadow': 'none',
    '--official-placeholder-color': 'rgba(0, 0, 0, 0.25)',
    '--official-primary-bg': 'rgb(0, 185, 107)',
    '--official-primary-border-color': 'transparent',
    '--official-primary-color': '#fff',
    '--official-button-radius': '4px',
    '--official-button-border-width': '1px',
    '--official-primary-shadow': 'rgba(5, 213, 88, 0.12) 0 2px 0',
    '--official-button-font-weight': '400',
    '--official-button-text-transform': 'none',
    '--official-danger-bg': '#fff',
    '--official-danger-color': 'rgb(255, 77, 79)',
    '--official-danger-border-color': 'rgb(255, 77, 79)',
    '--official-danger-radius': '4px',
    '--official-danger-shadow': 'rgba(255, 38, 5, 0.06) 0 2px 0',
    '--official-checkbox-radius': '4px',
    '--official-scene-bg': 'url("https://mdn.alipayobjects.com/huamei_7uahnr/afts/img/A*iM6CQ496P3oAAAAAAAAAAAAADrJ8AQ/fmt.webp")',
    '--official-preview-panel-bg': 'rgb(255, 255, 255)',
    '--official-preview-panel-border': '1px solid rgb(217, 217, 217)',
    '--official-preview-panel-radius': '4px',
    '--official-preview-panel-shadow': 'rgba(31, 35, 41, 0.08) 0 4px 16px',
    '--official-surface-bg': 'rgb(255, 255, 255)',
    '--official-surface-border': '1px solid rgb(217, 217, 217)',
    '--official-surface-radius': '4px',
    '--official-surface-shadow': 'rgba(31, 35, 41, 0.08) 0 4px 16px',
    '--official-segmented-bg': 'rgba(0, 0, 0, 0.04)',
    '--official-segmented-selected-bg': 'rgb(255, 255, 255)',
    '--official-font-family': 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
};
