import type { OfficialThemeSkin } from './types';

export const muiSkin: OfficialThemeSkin = {
  id: 'mui',
  className: 'theme-skin-mui',
  vars: {
    '--official-control-bg': 'rgb(255, 255, 255)',
    '--official-control-color': 'rgba(0, 0, 0, 0.87)',
    '--official-control-border-color': 'rgba(0, 0, 0, 0.23)',
    '--official-control-border-width': '1px',
    '--official-control-radius': '4px',
    '--official-control-height': '32px',
    '--official-control-shadow': 'none',
    '--official-placeholder-color': 'rgba(33, 33, 33, 0.26)',
    '--official-primary-bg': 'rgb(25, 118, 210)',
    '--official-primary-border-color': 'transparent',
    '--official-primary-color': '#fff',
    '--official-button-radius': '2px',
    '--official-button-border-width': '0',
    '--official-primary-shadow': 'rgba(0, 0, 0, 0.2) 0 3px 1px -2px, rgba(0, 0, 0, 0.14) 0 2px 2px, rgba(0, 0, 0, 0.12) 0 1px 5px',
    '--official-button-font-weight': '500',
    '--official-button-text-transform': 'uppercase',
    '--official-danger-bg': 'rgb(211, 47, 47)',
    '--official-danger-color': 'rgb(255, 255, 255)',
    '--official-danger-border-color': 'transparent',
    '--official-danger-radius': '4px',
    '--official-danger-border-width': '0',
    '--official-danger-shadow': 'var(--official-primary-shadow)',
    '--official-checkbox-radius': '4px',
    '--official-scene-bg': 'url("https://mdn.alipayobjects.com/huamei_iwk9zp/afts/img/A*IFkZRpIKEEkAAAAAQzAAAAgAegCCAQ/original")',
    '--official-preview-panel-bg': 'rgb(255, 255, 255)',
    '--official-preview-panel-border': '1px solid rgba(0, 0, 0, 0.12)',
    '--official-preview-panel-radius': '4px',
    '--official-preview-panel-shadow': 'rgba(0, 0, 0, 0.2) 0 3px 1px -2px, rgba(0, 0, 0, 0.14) 0 2px 2px, rgba(0, 0, 0, 0.12) 0 1px 5px',
    '--official-surface-bg': 'rgb(255, 255, 255)',
    '--official-surface-border': '1px solid rgba(0, 0, 0, 0.12)',
    '--official-surface-radius': '4px',
    '--official-surface-shadow': 'rgba(0, 0, 0, 0.2) 0 3px 1px -2px, rgba(0, 0, 0, 0.14) 0 2px 2px, rgba(0, 0, 0, 0.12) 0 1px 5px',
    '--official-segmented-bg': 'rgba(0, 0, 0, 0.04)',
    '--official-segmented-selected-bg': 'rgb(255, 255, 255)',
    '--official-font-family': 'Roboto, Helvetica, Arial, sans-serif',
  },
};
