import type { OfficialThemeSkin } from './types';

export const shadcnSkin: OfficialThemeSkin = {
  id: 'shadcn',
  className: 'theme-skin-shadcn',
  vars: {
    '--official-control-bg': 'rgb(255, 255, 255)',
    '--official-control-color': 'rgb(24, 24, 27)',
    '--official-control-border-color': 'rgb(228, 228, 231)',
    '--official-control-border-width': '1px',
    '--official-control-radius': '6px',
    '--official-picker-radius': '10px',
    '--official-control-height': '32px',
    '--official-control-shadow': 'none',
    '--official-placeholder-color': 'rgb(163, 163, 163)',
    '--official-primary-bg': 'rgb(24, 24, 27)',
    '--official-primary-border-color': 'rgb(24, 24, 27)',
    '--official-primary-color': '#fff',
    '--official-button-radius': '6px',
    '--official-button-border-width': '1px',
    '--official-primary-shadow': 'none',
    '--official-button-font-weight': '500',
    '--official-button-text-transform': 'none',
    '--official-danger-bg': 'rgb(220, 38, 38)',
    '--official-danger-color': '#fff',
    '--official-danger-border-color': 'rgb(220, 38, 38)',
    '--official-danger-radius': '6px',
    '--official-danger-shadow': 'none',
    '--official-checkbox-radius': '4px',
    '--official-scene-bg': 'url("https://mdn.alipayobjects.com/huamei_iwk9zp/afts/img/A*56tPQbwgFyEAAAAARuAAAAgAegCCAQ/original")',
    '--official-preview-panel-bg': 'rgb(255, 255, 255)',
    '--official-preview-panel-border': '1px solid rgb(228, 228, 231)',
    '--official-preview-panel-radius': '14px',
    '--official-preview-panel-shadow': 'none',
    '--official-surface-bg': 'rgb(255, 255, 255)',
    '--official-surface-border': '1px solid rgb(228, 228, 231)',
    '--official-surface-radius': '14px',
    '--official-surface-shadow': 'none',
    '--official-segmented-bg': 'rgba(0, 0, 0, 0.04)',
    '--official-segmented-selected-bg': 'rgb(255, 255, 255)',
    '--official-font-family': 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
};
