import type { OfficialThemeSkin } from './types';

export const v4Skin: OfficialThemeSkin = {
  id: 'v4',
  className: 'theme-skin-v4',
  vars: {
    '--official-control-bg': 'rgb(255, 255, 255)',
    '--official-control-color': 'rgba(0, 0, 0, 0.85)',
    '--official-control-border-color': 'rgb(217, 217, 217)',
    '--official-control-border-width': '1px',
    '--official-control-radius': '2px',
    '--official-control-height': '32px',
    '--official-control-shadow': 'none',
    '--official-placeholder-color': 'rgba(0, 0, 0, 0.25)',
    '--official-primary-bg': 'rgb(24, 144, 255)',
    '--official-primary-border-color': 'transparent',
    '--official-primary-color': '#fff',
    '--official-button-radius': '2px',
    '--official-button-border-width': '1px',
    '--official-primary-shadow': 'rgba(5, 175, 255, 0.1) 0 2px 0',
    '--official-button-font-weight': '400',
    '--official-button-text-transform': 'none',
    '--official-danger-bg': '#fff',
    '--official-danger-color': 'rgb(255, 77, 79)',
    '--official-danger-border-color': 'rgb(255, 77, 79)',
    '--official-danger-radius': '2px',
    '--official-danger-shadow': 'rgba(255, 38, 5, 0.06) 0 2px 0',
    '--official-checkbox-radius': '2px',
    '--official-scene-bg': 'linear-gradient(135deg, #eef8ff 0%, #ffffff 45%, #f6fbff 100%)',
    '--official-preview-panel-bg': 'rgb(255, 255, 255)',
    '--official-preview-panel-border': '1px solid rgb(217, 217, 217)',
    '--official-preview-panel-radius': '2px',
    '--official-preview-panel-shadow': 'rgba(0, 0, 0, 0.08) 0 4px 12px',
    '--official-surface-bg': 'rgb(255, 255, 255)',
    '--official-surface-border': '1px solid rgb(217, 217, 217)',
    '--official-surface-radius': '2px',
    '--official-surface-shadow': 'rgba(0, 0, 0, 0.08) 0 4px 12px',
    '--official-segmented-bg': 'rgba(0, 0, 0, 0.04)',
    '--official-segmented-selected-bg': 'rgb(255, 255, 255)',
    '--official-font-family': 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
};
